In [19]:
# reading data and working with arrays
import zarr
import numpy as np
from scipy.ndimage import map_coordinates, zoom, gaussian_filter

# data paths
inv_transform_path = '/nrs/scicompsoft/goinac/multifish/tiny/results/registration/local/t1-t2/inv-deform.n5'
inv_transform_subpath = 't2/c1/s2'
coords_path = '/nrs/scicompsoft/goinac/multifish/tiny/results/spots/t2/spots-c0-coord.csv'

# load fix data and spacing
inv_transform_zarr = zarr.open(store=zarr.N5Store(inv_transform_path), mode='r')
inv_transform = inv_transform_zarr[inv_transform_subpath]

input_coords = np.float32(np.loadtxt(coords_path, delimiter=','))
zyx_coords = np.empty_like(input_coords)
zyx_coords[:, 0:3] = input_coords[:, [2, 1, 0]]
zyx_coords[:, 3:] = input_coords[:, 3:]
coordinates = zyx_coords[:, 0:3]

In [ ]:
t = inv_transform[..., 0]

In [17]:
print(coordinates)

[[  5.30586   17.194525   1.240321]
 [ 24.841278  19.820435   2.564408]
 [ 24.418633  22.460075   2.589501]
 ...
 [ 54.406086 186.52228   74.75403 ]
 [ 57.075356 201.64537  232.02138 ]
 [ 61.216553 209.28227  254.73798 ]]


In [56]:
ct = coordinates.transpose()
ndims = inv_transform.shape[-1]
interp = lambda x: map_coordinates(x, ct, mode='nearest')


In [57]:
l = [interp(inv_transform[..., i]) for i in range(ndims)]
dx = np.array(l).transpose()

In [69]:
print(inv_transform[0:2,0:2,0:2,:].shape)
print('----------------------')
print(inv_transform[0:2,0:2,0:2,0].shape)
print('----------------------')
print(inv_transform[0:2,0:2,0:2,1])
print('----------------------')
print(inv_transform[0:2,0:2,0:2,2])

(2, 2, 2, 3)
----------------------
(2, 2, 2)
----------------------
[[[2.0620213 2.0748599]
  [2.066321  2.0796707]]

 [[2.0757468 2.088616 ]
  [2.0800672 2.0934749]]]
----------------------
[[[6.312518  6.3731275]
  [6.3418775 6.4031396]]

 [[6.3824697 6.443789 ]
  [6.4120784 6.4740877]]]


In [70]:
help(map_coordinates)

Help on function map_coordinates in module scipy.ndimage._interpolation:

map_coordinates(input, coordinates, output=None, order=3, mode='constant', cval=0.0, prefilter=True)
    Map the input array to new coordinates by interpolation.
    
    The array of coordinates is used to find, for each point in the output,
    the corresponding coordinates in the input. The value of the input at
    those coordinates is determined by spline interpolation of the
    requested order.
    
    The shape of the output is derived from that of the coordinate
    array by dropping the first axis. The values of the array along
    the first axis are the coordinates in the input array at which the
    output value is found.
    
    Parameters
    ----------
    input : array_like
        The input array.
    coordinates : array_like
        The coordinates at which `input` is evaluated.
    output : array or dtype, optional
        The array in which to place the output, or the dtype of the
        re

In [ ]:
    results = np.empty_like(permuted_results)
    results[original_points_indexes] = permuted_results


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 ...
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
